export const opciones = {
  ocacion: [
    "Cumpleaños",
    "Condolencias",
    "Día de las madres",
    "Aniversarios",
    "Nuevo Bebé",
    "Reconciliación",
    "Agradecimiento",
    "Graduación",
    "Día de Muertos",
    "San Valentín",
    "Corporativo",
    "Boda",
  ],
  Tamano: ["Pequeño", "Mediano", "Grande"],
  color: [
    "Rojo",
    "Blanco",
    "Amarillo",
    "Rosa",
    "Azul",
    "Verde",
    "Naranja",
    "Morado",
    "Lavanda",
    "Coral",
    "Durazno",
    "Violeta",
    "Fucsia",
    "Burgundy",
    "Crema",
    "Champán",
  ],
  estilo: [
    "Moderno",
    "Minimalista",
    "Rustico",
    "Elegante",
    "Clasico",
    "Vintage",
  ],
  floresYTipos: [
    "Rosas",
    "Tulipanes",
    "Orquídeas",
    "Lirios",
    "Margaritas",
    "Girasoles",
    "Claveles",
    "Hortensias",
    "Peonías",
    "Gladiolos",
    "Fresias",
    "Gerberas",
    "Crisantemos",
    "Anémonas",
    "Dalias",
    "Lavanda",
    "Jazmines",
    "Gardenias",
    "Alstroemerias",
    "Flor de Loto",
  ],
  personalida: [
    "Alegre",
    "Romantico",
    "Elegante",
    "Encantador",
    "Tranquilo",
    "Dulce",
    "Atrevido",
    "Aventurero",
    "Exótico",
    "Juvenil",
  ],
};
